### PR TITLE
Support Minecraft Java Edition 1.19

### PR DESCRIPTION
**Pull request by 7coil**
It's me again... again!

This PR bumps dependencies to their latest versions, and additionally uses the TerraformersMC maven repositories instead of Curseforge.

~~NB. Other than basic singleplayer autofishing (with a single rod), no other feature has been tested.~~
Multiplayer and Singleplayer autofishing seem to work fine.
This is just an update to make the existing mod functional with the latest and greatest update.

EDIT: Unofficial builds now available @ https://github.com/7coil/autofish/releases/tag/1.19-fabric

### CODE REVIEW

**Comment by 7coil** [comment]
For your sanity, I recommend squashing these commits because there's some past commits in the pile for some reason...

**Comment by PRRB** [comment]
Minecrash is crashing while autofishing with the snapshot build you posted above @7coil 

It's quite intermittent e.g. fish for 10-30 mins, minecraft randomly crashes.

Sorry I don't have the crash report here, I'll post it if I get it again. The log for sure had a reference to autofish at the top of the callstack though. It's a single-player only installation.

**Comment by 7coil** [comment]
Sounds like a pickle!

I'll see if I can reproduce the error, but the callstack would totally be helpful.

**Comment by PRRB** [comment]
[crash-2022-06-18_16.17.00-server.txt](https://github.com/MrTroot/autofish/files/8942872/crash-2022-06-18_16.17.00-server.txt)
[crash-2022-06-18_17.57.44-server.txt](https://github.com/MrTroot/autofish/files/8942873/crash-2022-06-18_17.57.44-server.txt)
[crash-2022-06-19_14.37.29-server.txt](https://github.com/MrTroot/autofish/files/8942874/crash-2022-06-19_14.37.29-server.txt)
Here you go! Didn't realize the crash dumps are saved in game dir automatically.

**Comment by 7coil** [comment]
Eek!

Sounds like something to look for then.
Thanks for the help.

**Comment by 7coil** [comment]
I haven't been able to reproduce the bug **yet**, even after an hour.
Does the bug still exist when you only have the mod installed by itself?

**Comment by 7coil** [comment]
Sounds like it's still a thing; Keep following on #33

**Pull request merged**
